# Generated by Django 3.1 on 2020-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas3k_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=2, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
