# Generated by Django 3.1 on 2020-09-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas3k_test', '0002_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('tittle', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtittle', models.CharField(max_length=150, verbose_name='Подзаголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Заметки',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
