# Generated by Django 3.1 on 2020-09-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vas3k_test', '0006_auto_20200905_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
