# Generated by Django 3.1 on 2020-09-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas3k_test', '0009_auto_20200910_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
