# Generated by Django 3.1 on 2020-09-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vas3k_test', '0010_post_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('tittle', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtittle', models.CharField(max_length=150, verbose_name='Подзаголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('test', models.IntegerField(verbose_name=[1])),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vas3k_test.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Путешествия',
                'verbose_name_plural': 'Путешествия',
            },
        ),
    ]
