# Generated by Django 3.1 on 2020-09-22 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas3k_test', '0012_challenge_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 17, 17, 53, 168041), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 17, 17, 53, 167042), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 17, 17, 53, 166043), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='travel',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 17, 17, 53, 167042), verbose_name='Дата публикации'),
        ),
    ]
